# Generated by Django 6.0.8 on 2026-08-08 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_issue_id', models.BigIntegerField(unique=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('repo_full_name', models.CharField(max_length=255)),
                ('repo_avatar_url', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('labels', models.CharField(blank=True, max_length=500)),
                ('foundation', models.CharField(blank=True, help_text='CNCF, Apache, Linux Foundation, ...', max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Confirmé')], default='intermediate', max_length=20)),
                ('is_assigned', models.BooleanField(default=False)),
                ('stars_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('repo_size_kb', models.IntegerField(default=0)),
                ('avg_response_time_hours', models.FloatField(blank=True, null=True)),
                ('pr_acceptance_rate', models.FloatField(blank=True, null=True)),
                ('beginner_friendly_score', models.FloatField(blank=True, null=True)),
                ('has_contributing', models.BooleanField(default=False)),
                ('has_code_of_conduct', models.BooleanField(default=False)),
                ('issue_updated_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-stars_count'],
                'indexes': [models.Index(fields=['language'], name='core_issue_languag_67e9f4_idx'), models.Index(fields=['difficulty'], name='core_issue_difficu_0685f4_idx'), models.Index(fields=['is_assigned'], name='core_issue_is_assi_89bea8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('pr_url', models.URLField()),
                ('kind', models.CharField(choices=[('feature', 'Fonctionnalité'), ('bugfix', 'Correction de bug'), ('docs', 'Documentation'), ('refactor', 'Refactoring'), ('other', 'Autre')], default='other', max_length=20)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='core.issue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('headline', models.CharField(blank=True, help_text='Courte accroche affichée sur le profil', max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
