# Generated by Django 6.0.8 on 2026-08-20 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['user', '-created_at'], name='core_contri_user_id_097d17_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['merged_at'], name='core_contri_merged__9819cd_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_assigned', 'language'], name='core_issue_is_assi_fdc04b_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_assigned', 'difficulty'], name='core_issue_is_assi_f60a64_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['foundation'], name='core_issue_foundat_f22b38_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['-stars_count'], name='core_issue_stars_c_848246_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['-beginner_friendly_score'], name='core_issue_beginne_1b8e12_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country'], name='core_profil_country_d728ff_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['github_username'], name='core_profil_github__b3ca80_idx'),
        ),
    ]
